name: contact_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  gallery_saver: ^2.3.2
  image_cropper: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
